name: Update My GitHub Profile

on:
  schedule: # 03:00 JST == 18:00 UTC
    - cron: "0 18 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Pull articles from Qiita
        run: npx rimraf ./public/.remote && npx qiita pull -f
        env:
          QIITA_TOKEN: ${{ secrets.QIITA_TOKEN }}
      - name: Update Index
        run: npm run create-index
        env:
          QIITA_TOKEN: ${{ secrets.QIITA_TOKEN }}
      - uses: yoshi389111/github-profile-3d-contrib@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
          MAX_REPOS: 200
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: header, activity, community, repositories, metadata
          output_action: none
          filename: metrics/metrics.base.svg
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics/details.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 10
          plugin_followup: yes
          plugin_followup_indepth: yes
          output_action: none
      - name: Commit & Push
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git add -A .
          if git commit -m "${COMMIT_MESSAGE}"; then
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMIT_MESSAGE: "Update GitHub profile"
